test_set_rate: 0.33
model_path: "challenge/models"
model_version: "v1"
threshold_in_minutes: 15.0
categorical_features:
  - OPERA
  - TIPOVUELO
  - MES
expected_features:
  - OPERA_Latin American Wings
  - MES_7
  - MES_10
  - OPERA_Grupo LATAM
  - MES_12
  - TIPOVUELO_I
  - MES_4
  - MES_11
  - OPERA_Sky Airline
  - OPERA_Copa Air
default_model_params:
  # A value of 200 helps capture complex relationships in the data without overfitting excessively.
  n_estimators: 200
  # Setting it to 8 limits the complexity of each tree, helping to prevent overfitting.
  max_depth: 8
  # A value of 0.1 provides a good balance between convergence speed and training stability.
  learning_rate: 0.01
  # random_state: Seed used for random number generation to ensure reproducibility.
  random_state: 1
  use_label_encoder: false
  eval_metric: logloss