name: 'Continuous Delivery'

on:
  # Deploy automatically on push to main
  push:
    branches: [ "main" ]

jobs:
  build_deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3. Create venv and install dependencies
      - name: Setup Virtual Environment and Install Dependencies
        run: |
          make venv
          source .venv/bin/activate
          make install

      # 4. Authenticate to GCP using service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5. Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          skip_install: false
          version: latest

      # 6. Configure Docker to use gcloud as a credential helper
      - name: Configure Docker
        run: |
          gcloud auth configure-docker gcr.io --quiet

      # 7. Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/my-latam-api:latest .

      # 8. Push the image to GCR
      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.PROJECT_ID }}/my-latam-api:latest

      # 9. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image gcr.io/${{ secrets.PROJECT_ID }}/my-latam-api:latest \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated \
            --port 8000 \
            --set-env-vars PORT=8000

      # 10. Run stress test
      - name: Run stress test
        run: |
          source .venv/bin/activate
          make stress-test

      # 11. Upload coverage as an artifact 
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
          retention-days: 3